### ISSUE TITLE
Seeing a panic on sign-and-notarize

### ISSUE THREAD

**Issue by matthewmueller** [anchore/quill#529]
Hi there, 

**What happened**:

```
quill sign-and-notarize dist/dot_0.0.1_darwin_arm64/dot
Caught panic:

interface conversion: tea.Model is frame.Frame, not *frame.Frame

Restoring terminal...

goroutine 11 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.23.2/x64/src/runtime/debug/stack.go:26 +0x64
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.23.2/x64/src/runtime/debug/stack.go:18 +0x1c
github.com/charmbracelet/bubbletea.(*Program).recoverFromPanic(0x14000562500)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.1/tea.go:705 +0x84
panic({0x1032bffa0?, 0x14000612090?})
        /opt/hostedtoolcache/go/1.23.2/x64/src/runtime/panic.go:785 +0x124
github.com/anchore/quill/cmd/quill/internal/ui.(*UI).Update(0x140005e65a0, {0x1033500c0, 0x1400013ab80})
        /home/runner/work/quill/quill/cmd/quill/internal/ui/ui.go:173 +0x7e4
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0x14000562500, {0x1033f9ff8?, 0x140005e65a0?}, 0x14000042380)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.1/tea.go:461 +0x6a8
github.com/charmbracelet/bubbletea.(*Program).Run(0x14000562500)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.1/tea.go:595 +0x8cc
github.com/anchore/quill/cmd/quill/internal/ui.(*UI).Setup.func1()
        /home/runner/work/quill/quill/cmd/quill/internal/ui/ui.go:62 +0x54
created by github.com/anchore/quill/cmd/quill/internal/ui.(*UI).Setup in goroutine 1
        /home/runner/work/quill/quill/cmd/quill/internal/ui/ui.go:60 +0x1d4
notarization failed: binary is not signed thus will not pass notarization
```

**What you expected to happen**:

DIdn't expect the panic

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Not sure, it's my first time trying this tool :) 

**Environment**: 
- Output of `version` command: `go version go1.23.0 darwin/arm64`
- OS (e.g: `cat /etc/os-release` or similar): OSX

**Comment by kzantow** [comment]
Hi @matthewmueller which quill version is this?

**Comment by matthewmueller** [comment]
Most likely latest. I just ran the install script and tried to sign and
notorize

**Comment by steckes** [comment]
Just ran into the same error on quill 0.5.0 macOS 15.2

**Comment by steckes** [comment]
I just ran quill sign mylib.dylib and got this:

```
quill sign libaic.dylib
Caught panic:

interface conversion: tea.Model is frame.Frame, not *frame.Frame

Restoring terminal...

goroutine 53 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.23.2/x64/src/runtime/debug/stack.go:26 +0x64
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.23.2/x64/src/runtime/debug/stack.go:18 +0x1c
github.com/charmbracelet/bubbletea.(*Program).recoverFromPanic(0x140006ac500)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.1/tea.go:705 +0x84
panic({0x101b3bfa0?, 0x1400046e030?})
        /opt/hostedtoolcache/go/1.23.2/x64/src/runtime/panic.go:785 +0x124
github.com/anchore/quill/cmd/quill/internal/ui.(*UI).Update(0x140001b2b40, {0x101bcc0c0, 0x140005b0040})
        /home/runner/work/quill/quill/cmd/quill/internal/ui/ui.go:173 +0x7e4
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0x140006ac500, {0x101c75ff8?, 0x140001b2b40?}, 0x140005582a0)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.1/tea.go:461 +0x6a8
github.com/charmbracelet/bubbletea.(*Program).Run(0x140006ac500)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.1/tea.go:595 +0x8cc
github.com/anchore/quill/cmd/quill/internal/ui.(*UI).Setup.func1()
        /home/runner/work/quill/quill/cmd/quill/internal/ui/ui.go:62 +0x54
created by github.com/anchore/quill/cmd/quill/internal/ui.(*UI).Setup in goroutine 1
        /home/runner/work/quill/quill/cmd/quill/internal/ui/ui.go:60 +0x1d4
```

**Comment by tecimovic** [comment]
I see the same error on latest. Wasn't there 2 months ago. I suspect something related to updating all the packages.

**Comment by tecimovic** [comment]
I did 'git bisect' and the above comment shows the offending commit.
@wagoodman  ?

**Comment by robindiddams** [comment]
just ran into this too.  this only happens when you **dont** specify verbose. so easy workaround is `-v` and youre good to go

**Comment by wagoodman** [comment]
Thanks for reporting and debugging! I've got a fix posted and will cut a release once it's merged.
